[project]
name = "expense-tracker"
version = "0.1.0"
description = "Personal expense and income tracker"
authors = [
    { name = "Anderson R Damasceno", email = "anderdam@gmail.com" }
]
requires-python = ">=3.11"
keywords = ["finance", "tracker", "personal", "budget"]

dependencies = [
  "fastapi>= 0.119.0",
  "uvicorn[standard]>=0.37.0",
  "sqlalchemy>=2.0.44",
  "asyncpg>=0.30.0",
  "pydantic>=2.12.0",
  "psycopg2-binary>=2.9.11",
  "alembic>=1.17.0",
  "python-dotenv>=1.1.1",
  "richer>=0.1.6",
  "streamlit>=1.50.0",
  "requests>=2.32.5",
  "pydantic_settings >=2.11"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
  "httpx>=0.28.1",
  "black>=25.9.0",
  "isort>=7.0.0",
  "ruff>=0.14.0",
  "mypy>=1.18.2",
  "pre-commit>=4.3.0",
  "bandit>=1.8.6"
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 88
target-version = "py311"
lint.select = ["E", "F", "B", "I"]
lint.ignore = ["E501"]  # line too long (handled by black)

#[tool.mypy]
#python_version = "3.11"
#strict = true
#warn_unused_configs = true
#disallow_untyped_defs = true
#disallow_incomplete_defs = true
#check_untyped_defs = true
#show_error_codes = true
#plugins = ["pydantic.mypy"]
#ignore_missing_imports = true


[tool.setuptools]
packages = ["app"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = ["pyproject.toml:version"]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
tag_format = "v$version"
commit_message = "{{commit_type}}{{scope}}: {{commit_subject}}"

[tool.commitizen.customize]
# Optional: override default section titles
[tool.commitizen.customize.commit_parser]
# Define how commit types map to changelog sections
feat = "âœ¨ Features"
fix = "ğŸ› Fixes"
chore = "ğŸ§¹ Chores"
refactor = "ğŸ”§ Refactoring"
docs = "ğŸ“ Documentation"
style = "ğŸ’„ Style"
test = "âœ… Tests"
perf = "âš¡ Performance"
ci = "ğŸ” CI/CD"
build = "ğŸ—ï¸ Build"
revert = "âª Reverts"
